# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
bbuild_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Visonic Proxy"
  org.opencontainers.image.description: "Addon to provide proxy for Visonic Alarm"
  org.opencontainers.image.source: "https://github.com/msp1974/visonic_proxy"
  org.opencontainers.image.licenses: "Apache License 2.0"
