name: "Visonic Proxy"
description: "Visonic Proxy Server for Using Powerlink with Visonic Integration"
version: "1.0.5"
slug: "visonic_proxy"
url: https://github.com/msp1974/visonic_proxy
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: false
ports:
  5001/tcp: 5001
  5002/tcp: 5002
  8082/tcp: 8082
  8443/tcp: 8443
ports_description:
  5001/tcp: Alarm connection
  5002/tcp: Monitor socket connection
  8082/tcp: Websocket connection (if enabled)
  8443/tcp: Alarm web connection
map:
  - addon_config:rw
legacy: true
options:
  visonic_host: "52.58.105.181"
  websocket_mode: true
  message_log_level: 1
  log_level: "info"
  
schema:
  visonic_host: str
  websocket_mode: bool
  message_log_level: "int(1,5)"
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  
  
  
