name: "Visonic Proxy"
description: "Visonic Proxy Server for Using Powerlink with Visonic Integration"
version: "1.0.2"
slug: "visonic_proxy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
ports:
  5001/tcp: 5001
  5002/tcp: 5002
  8443/tcp: 8443
legacy: true
