---
    # yamllint disable rule:line-length rule:truthy
    name: Build add-on
    
    env:
      BUILD_ARGS: "--test"
      MONITORED_FILES: "apparmor.txt build.yaml config.yaml Dockerfile data rootfs"
    
    on:
      pull_request:
        branches: ["dev","master"]
      push:
        branches: ["dev","master"]
    
    jobs:
      init:
        runs-on: ubuntu-latest
        name: Initialize builds
        outputs:
          changed_files: ${{ steps.changed_files.outputs.all }}
        steps:
          - name: Check out the repository
            uses: actions/checkout@v4.2.2
    
          - name: Get changed files
            id: changed_files
            uses: masesgroup/retrieve-changed-files@v3.0.0
    
      build:
        needs: init
        runs-on: ubuntu-latest
        name: Build ${{ matrix.arch }} for Visonic Proxy add-on
        strategy:
          matrix:
            arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    
        steps:
          - name: Check out repository
            uses: actions/checkout@v4.2.2
    
          - name: Get information
            id: info
            uses: home-assistant/actions/helpers/info@master
    
          - name: Check add-on
            id: check
            run: |
              if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
                 echo "build_arch=true" >> "$GITHUB_OUTPUT";
               else
                 echo "${{ matrix.arch }} is not a valid arch for Visonic Proxy, skipping build";
              fi
    
          - name: Set build arguments
            if: steps.check.outputs.build_arch == 'true'
            run: |
              if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
                  echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
              fi
    
          - name: Login to DockerHub
            if: env.BUILD_ARGS == '--docker-hub-check'
            uses: docker/login-action@v3.3.0
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
    
          - name: Build Visonic Proxy add-on
            if: steps.check.outputs.build_arch == 'true'
            uses: home-assistant/builder@2024.08.2
            with:
              args: |
                ${{ env.BUILD_ARGS }} \
                --${{ matrix.arch }} \
                --addon